// boards.config.js — generated by setup.js. Safe to hand-edit afterwards.
// Board IDs come from the Monday.com URL: .../boards/{id}

module.exports = {
  // Boards scanned for candidate matches.
  sourceBoardIds: [
    "18423031147",
  ],

  // Confirmed matches are written to this board.
  trackingBoardId: "18423031181",

  // Business unit that leads every comment
  // ("MTech interested to interview ...").
  businessUnit: "MTech",

  // Who to @mention per board. Entries are Monday user IDs or emails.
  tagUsersByBoard: {
    "18423031147": ["53435570"],
  },

  // Fallback taggers for any board not listed above.
  defaultTagUsers: [],

  // Minimum fraction of the job's required skills a CV must contain (0.0–1.0).
  skillThreshold: 0.7,
};
