'use strict';

// setup.js — first-run configuration wizard for DeepInsights.
//
// Walks a new user through everything the pipeline needs and writes two files:
//   • boards.config.js  — business unit, source boards, per-board taggers,
//                         tracking board, and the skill-match threshold
//   • .monday-token     — the Monday API token (gitignored)
//
// Run:  node setup.js   (or: npm run setup)

const fs = require('node:fs');
const path = require('node:path');
const readline = require('node:readline');
const { Writable } = require('node:stream');

// --- Prompt plumbing ---------------------------------------------------------
// A mutable output stream lets us hide typed characters for the token prompt.
const mutableOut = new Writable({
  write(chunk, enc, cb) {
    if (!mutableOut.muted) process.stdout.write(chunk, enc);
    cb();
  },
});
// Created inside main() so merely requiring this module (for tests) never grabs stdin.
let rl;

// Event-based line reader. Repeated rl.question() drops lines with piped (non-TTY)
// input, so we buffer 'line' events into a queue and hand them out one at a time —
// works identically for an interactive terminal and for piped input (tests).
const lineQueue = [];
const waiters = [];
let closed = false;
function onLine(line) {
  if (waiters.length) waiters.shift()(line);
  else lineQueue.push(line);
}
function nextLine() {
  if (lineQueue.length) return Promise.resolve(lineQueue.shift());
  if (closed) return Promise.resolve('');
  return new Promise((resolve) => waiters.push(resolve));
}

function ask(query, { hidden = false } = {}) {
  process.stdout.write(query);
  mutableOut.muted = hidden;
  return nextLine().then((line) => {
    mutableOut.muted = false;
    if (hidden) process.stdout.write('\n');
    return (line ?? '').trim();
  });
}

// --- Typed prompts (re-ask until valid) --------------------------------------
async function askNonEmpty(query) {
  for (;;) {
    const v = await ask(query);
    if (v) return v;
    console.log('  ✗ Please enter a value.');
  }
}

async function askInt(query, { min = 1 } = {}) {
  for (;;) {
    const v = await ask(query);
    const n = Number(v);
    if (Number.isInteger(n) && n >= min) return n;
    console.log(`  ✗ Please enter a whole number ≥ ${min}.`);
  }
}

async function askBoardId(query) {
  for (;;) {
    const v = await ask(query);
    if (/^\d+$/.test(v)) return v;
    console.log('  ✗ A Monday board ID is all digits (from the board URL .../boards/{id}).');
  }
}

async function askFraction(query, def) {
  for (;;) {
    const v = await ask(`${query} [${def}]: `);
    if (!v) return def;
    const n = Number(v);
    if (!Number.isNaN(n) && n >= 0 && n <= 1) return n;
    console.log('  ✗ Enter a decimal between 0.0 and 1.0 (e.g. 0.7).');
  }
}

// Parse a comma-separated list of taggers; warn on entries that are neither a
// numeric user ID nor an email (plain names don't resolve reliably at scale).
function parseTaggers(raw) {
  const entries = raw.split(',').map((s) => s.trim()).filter(Boolean);
  const looksWrong = entries.filter((e) => !/^\d+$/.test(e) && !e.includes('@'));
  if (looksWrong.length) {
    console.log(`  ⚠ These look like names, not IDs/emails, and may not resolve in a large account: ${looksWrong.join(', ')}`);
  }
  return entries;
}

const TAGGER_HINT =
  'comma-separated Monday user IDs or emails (e.g. 53435570, jane@ibm.com)';

// --- Config file generation --------------------------------------------------
const q = (s) => JSON.stringify(String(s));
const list = (arr) => `[${arr.map(q).join(', ')}]`;

function generateConfig(cfg) {
  const boardLines = cfg.sourceBoardIds.map((id) => `    ${q(id)},`).join('\n');
  const tagLines = Object.entries(cfg.tagUsersByBoard)
    .map(([id, users]) => `    ${q(id)}: ${list(users)},`)
    .join('\n') || '    // (none)';

  return `// boards.config.js — generated by setup.js. Safe to hand-edit afterwards.
// Board IDs come from the Monday.com URL: .../boards/{id}

module.exports = {
  // Boards scanned for candidate matches.
  sourceBoardIds: [
${boardLines}
  ],

  // Confirmed matches are written to this board.
  trackingBoardId: ${q(cfg.trackingBoardId)},

  // Business unit that leads every comment
  // ("${cfg.businessUnit} interested to interview ...").
  businessUnit: ${q(cfg.businessUnit)},

  // Who to @mention per board. Entries are Monday user IDs or emails.
  tagUsersByBoard: {
${tagLines}
  },

  // Fallback taggers for any board not listed above.
  defaultTagUsers: ${list(cfg.defaultTagUsers)},

  // Minimum fraction of the job's required skills a CV must contain (0.0–1.0).
  skillThreshold: ${cfg.skillThreshold},
};
`;
}

// --- Live token check (uses monday.js, which reads MONDAY_API_TOKEN first) ---
async function verifyToken(token) {
  process.env.MONDAY_API_TOKEN = token;
  const { mondayQuery } = require('../src/integrations/monday');
  const data = await mondayQuery('query { me { name email account { name } } }');
  return data.me;
}

// --- Wizard ------------------------------------------------------------------
async function main() {
  // terminal:true (a real TTY) gives line editing + hidden token entry; when input
  // is piped (isTTY false) we skip terminal mode so lines still read cleanly.
  rl = readline.createInterface({ input: process.stdin, output: mutableOut, terminal: !!process.stdin.isTTY });
  rl.on('line', onLine);
  rl.on('close', () => { closed = true; while (waiters.length) waiters.shift()(''); });
  console.log('\nDeepInsights — setup\n====================');
  console.log('This will create boards.config.js and .monday-token in the project root.\n');

  // 1. Business unit
  const businessUnit = await askNonEmpty('Business unit name (leads every comment, e.g. MTech): ');

  // 2. Source boards + per-board taggers
  const n = await askInt('\nHow many source boards do you want to scan? ', { min: 1 });
  const sourceBoardIds = [];
  const tagUsersByBoard = {};
  console.log(`\nFor each board, enter its ID then who to tag (${TAGGER_HINT}).`);
  for (let i = 1; i <= n; i++) {
    const id = await askBoardId(`\n  Board ${i}/${n} — board ID: `);
    sourceBoardIds.push(id);
    const raw = await ask(`  Board ${i}/${n} — people to tag (${TAGGER_HINT}; blank for none): `);
    const taggers = parseTaggers(raw);
    if (taggers.length) tagUsersByBoard[id] = taggers;
  }

  // 3. Default fallback taggers
  const defRaw = await ask(`\nFallback taggers for any board without its own list (${TAGGER_HINT}; blank for none): `);
  const defaultTagUsers = parseTaggers(defRaw);

  // 4. Output / tracking board
  const trackingBoardId = await askBoardId('\nOutput (tracking) board ID — where confirmed matches are logged: ');

  // 5. Matching threshold
  const skillThreshold = await askFraction(
    '\nSkill-match threshold — fraction of required skills a CV must contain (0.0–1.0)',
    0.7
  );

  // 6. Monday token (hidden) + live check
  console.log('\nMonday API token — avatar → Developers → My Access Tokens.');
  let token = '';
  while (!token) {
    token = await ask('  Paste token (input hidden): ', { hidden: true });
    if (!token) console.log('  ✗ Please paste a token.');
  }

  process.stdout.write('  Verifying token against Monday… ');
  try {
    const me = await verifyToken(token);
    console.log(`✓ connected as ${me.name} (${me.account?.name || 'account'})`);
  } catch (err) {
    console.log(`✗ failed: ${err.message}`);
    const cont = await ask('  Save anyway? (y/N): ');
    if (!/^y/i.test(cont)) {
      console.log('\nAborted — nothing written.');
      rl.close();
      return;
    }
  }

  // 7. Confirm before overwriting existing files (written to the repo root, one level up)
  const root = path.join(__dirname, '..');
  const targets = ['boards.config.js', '.monday-token'];
  const existing = targets.filter((f) => fs.existsSync(path.join(root, f)));
  if (existing.length) {
    console.log(`\n⚠ These file(s) already exist and will be overwritten: ${existing.join(', ')}`);
    const ok = await ask('  Overwrite? (y/N): ');
    if (!/^y/i.test(ok)) {
      console.log('\nAborted — nothing written.');
      rl.close();
      return;
    }
  }

  // 8. Write files
  const configText = generateConfig({
    businessUnit,
    sourceBoardIds,
    tagUsersByBoard,
    defaultTagUsers,
    trackingBoardId,
    skillThreshold,
  });
  fs.writeFileSync(path.join(root, 'boards.config.js'), configText);
  fs.writeFileSync(path.join(root, '.monday-token'), token + '\n');

  console.log('\n✓ Wrote boards.config.js and .monday-token');
  console.log('\nSetup summary:');
  console.log(`  Business unit : ${businessUnit}`);
  console.log(`  Source boards : ${sourceBoardIds.length} (${sourceBoardIds.join(', ')})`);
  console.log(`  Tracking board: ${trackingBoardId}`);
  console.log(`  Threshold     : ${skillThreshold} (${Math.round(skillThreshold * 100)}%)`);
  console.log('\nNext: preview a run with');
  console.log("  node src/index.js 'examples/job-ad.txt'        (dry-run — writes nothing)");
  console.log("  node src/index.js 'examples/job-ad.txt' --post (posts comments + logs matches)");

  rl.close();
}

module.exports = { generateConfig, parseTaggers };

if (require.main === module) {
  main().catch((err) => {
    console.error('\nSetup error:', err.message);
    if (rl) rl.close();
    process.exit(1);
  });
}
